name: Release
# This workflow helps with creating releases.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Create release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist --release-notes ./RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
